id: P009330
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W28960
  title: འགོས་ལོ་གཞོན་ནུ་དཔལ་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    79289a52be9f42bdb5fcb3fe13dd5ee1:
      image_group_id: I5833
      title: ''
      volume_number: 1
      total_pages: 189
      base_file: v001.txt
